<a href="https://colab.research.google.com/github/RogerioTiuma/EspecializacaoCesar/blob/main/Dados_Aula_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Olá, mundo")

Olá, mundo


# Numpy

In [7]:
import time
start_time = time.time()
a = range(10000000)
b = range(10000000)
c = []

for i in range(len(a)):
  c.append(a[i]+b[i])

elpased_time = time.time() - start_time
print(elpased_time)

3.923311471939087


In [14]:
import numpy as np

start_time = time.time()
a = np.arange(10000000)
b = np.arange(10000000)
c = []

c = a + b

elpased_time = time.time() - start_time
print(elpased_time)

0.08025550842285156


# Criação de Arrays

In [15]:
#Criar um array NumPy a partir de uma lista
lista = range(1,6)
array_lista = np.array(lista)
print(f"Array criado a partir de uma lista: {array_lista}")

Array criado a partir de uma lista: [1 2 3 4 5]


In [ ]:
# Criar um array de zeros com forma específica (3x4)
array_zero = np.zeros((3,4))
print(array_zero)

In [18]:
# Criar um array de uns com forma específica (2x2)
array_uns = np.ones((2,2))
print(array_uns)

[[1. 1.]
 [1. 1.]]


In [23]:
# Criar um array com valores igualmente espaçados no intervalo de 8 à 9 (exclusivo)
array_arange = np.arange(0,15,2)
print(array_arange)

[ 0  2  4  6  8 10 12 14]


In [25]:
# Criar um array com valores igualmente espaçados entre 0 e 1 com 5 elementos
array_linspace = np.linspace(0,1,5)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


# Operações Matemáticas

In [27]:
#Criando dois arrays
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [28]:
# Adição
soma = array1 + array2
print(f"Soma: {soma}")

Soma: [5 7 9]


In [29]:
# Subtração
subtracao = array1 - array2
print(f"Subtracao: {subtracao}")

Soma: [-3 -3 -3]


In [30]:
# Multiplicação
multiplicacao = array1 * array2
print(f"Multiplicacao: {multiplicacao}")

Multiplicacao: [ 4 10 18]


In [31]:
# Produto escalar
produto_escalar = np.dot(array1, array2)
print(f"Produto escalar: {produto_escalar}")

Produto escalar: 32


# Indexação e Fatiamento

In [33]:
# Crie um array NumPy com valores de 0 a 9
arr = np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [34]:
# Acesso ao elemento na posição 5 (índice 5)
elemento = arr[5]
print(elemento)

15


In [35]:
# Fatiamento: Selecione um subconjunto do array
# Do índice 2 (inclusivo) ao índice 7 (exclusivo)
subconjunto = arr[2:7]
print(subconjunto)

[12 13 14 15 16]


In [36]:
# Fatiamento: Selecione um subconjunto do array
# Do índice 2 (inclusivo) ao índice 9 (exclusivo) com passo 2
subconjunto_passo = arr[2:9:2]
print(subconjunto_passo)

[12 14 16 18]


# Funções Estatísticas

In [38]:
# Crie um array NumPy com valores de 0 a 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
# Selecionando o menor valor

menor = np.min(arr)
index_menor = np.argmin(arr)
print(f"Menor valor: {menor} no índice: {index_menor}")

Menor valor: 0 no índice: 0


In [42]:
# Selecionando o maior valor

maior = np.max(arr)
index_maior = np.argmax(arr)
print(f"Menor valor: {maior} no índice: {index_maior}")

Menor valor: 9 no índice: 9


In [43]:
# Calculando a média

media = np.mean(arr)
print(f"Média: {media}")

Média: 4.5


In [44]:
# Calculando a mediana

mediana = np.median(arr)
print(f"Mediana: {mediana}")

Mediana: 4.5


In [45]:
# Calculando o desvio padrão

desvio_padrao = np.std(arr)
print(f"Desvio Padrão: {desvio_padrao}")

Desvio Padrão: 2.8722813232690143


In [46]:
# Calculando a soma

soma = np.sum(arr)
print(f"Soma: {soma}")

Soma: 45


# Manipulação de Arrays

In [47]:
# Crie um array NumPy com valores de 0 a 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
# Redimensionando o array para uma matriz 2x5
matriz = np.reshape(arr, (10,1))
print(matriz)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [59]:
# Crie outro array numpy
arr2 = np.arange(10,20)
print(arr2)

[10 11 12 13 14 15 16 17 18 19]


# Gerador de Números Aleatórios

In [62]:
# Gerando 5 números aleatórios entre 0 e 1
random_numbers = np.random.rand(5)
print(random_numbers)

[0.29811051 0.70280827 0.13693732 0.09967484 0.507266  ]


In [63]:
# Gerando 5 números aleatórios em uma distribuição normal
random_numbers = np.random.randn(5)
print(random_numbers)

[ 0.0888997  -0.83579277 -1.20749433 -0.00536481  0.08244528]


In [65]:
# Gerando 5 números inteiros aleatórios entre 1 e 10
random_numbers = np.random.randint(1,11,5)
print(random_numbers)

[2 7 2 1 6]


In [66]:
# Gerando uma matriz 3x4 com números aleatórios entre 1 e 10
random_numbers = np.random.randint(1,11,(3,4))
print(random_numbers)

[[ 6  7  5  2]
 [ 8  8  5 10]
 [ 5  6 10  2]]


In [70]:
# Gerando matriz de números aleatórios reais entre 10 e 40 (uniforme)
random_numbers = np.random.uniform(10,40,30)
random_numbers = np.round(random_numbers, 2)
print(random_numbers)

[28.11 21.05 26.46 13.7  23.81 18.31 11.69 27.92 15.66 13.16 31.66 19.12
 30.08 30.07 21.07 34.64 13.27 35.23 13.97 25.54 38.92 17.85 38.1  33.45
 30.05 31.03 14.69 18.15 34.16 33.79]


# Álgebra Linear

In [71]:
# Calcular as diferenças discretas entre elementos consecutivo em um array
arr = np.array([2, 4, 7, 11, 16])
differences = np.diff(arr)
print(differences)

[2 3 4 5]


In [72]:
# Definindo uma matrz
matriz = np.array([[2,3],[1,4]])

# Calculando a matriz inversa
matriz_inversa = np.linalg.inv(matriz)

print(matriz)
print(matriz_inversa)

[[2 3]
 [1 4]]
[[ 0.8 -0.6]
 [-0.2  0.4]]


In [73]:
# Calculando o determinante

determinante = np.linalg.det(matriz)
print(determinante)

5.000000000000001


# Funções de Comparações

In [77]:
# Exemplo Básico
arr = np.array([1,2,3,4,5,6])

# Definir uma condição (True para elementos maiores que 3)
condicao = arr > 3
print(condicao)

# Usar np.where() para obter os índices que atendem à condição
resultado = np.where(condicao)
print(resultado)

# Ou
resultado = np.where(arr>3)
print(resultado)

[False False False  True  True  True]
(array([3, 4, 5]),)
(array([3, 4, 5]),)


In [78]:
# Exemplo de sunstituição

arr = np.array([1,2,3,4,5,6])

# Usar np.where() para substituir valores com base em uma condição
new_arr = np.where(arr < 3, arr, -1)
print(new_arr)

[ 1  2 -1 -1 -1 -1]


In [80]:
# Exemplo com condições multiplas
arr = np.array([1,2,3,4,5,6])

# usar np.where() com condições múltiplas
new_arr = np.where(arr<3, -1, np.where(arr > 4, 10, arr))
print(new_arr)

[-1 -1  3  4 10 10]


## Seleção e Filtragem

In [82]:
# Criando um array de exemplo
arr = np.arange(1,11)
print(arr)
# Selecione apenas os elementos maiores que 5
selecionados = arr[arr>5]
print(selecionados)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]


In [83]:
# Selecionando elementos pares
filtrados = arr[arr % 2 == 0]
print(filtrados)

[ 2  4  6  8 10]


In [85]:
# Selecionando elementos dentro de um intervalo
intervalo = arr[(arr >= 3) & (arr <= 7)]
print(intervalo)

[3 4 5 6 7]


Importe NumPy como np

Crie uma array de 10 zeros

Crie um array de inteiros de 10 até 50

Crie um array dos números pares de 10 até 50

Criei uma matriz 3x3 com valores variando de 0 até 8

Crie uma matriz identidade 3x3

Use NumPy para gerar números aleatórios entre 0 e 1

Inserir 5 números inteiros em um array a partir do input()

In [86]:
import numpy as np

In [88]:
array_inteiros = np.arange(10,51,2)
print(array_inteiros)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [90]:
matriz_3_3 = np.arange(9).reshape(3,3)
print(matriz_3_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [92]:
matriz_identidade = np.eye(3)
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [95]:
random_numbers = np.random.rand(1,11,5)
print(random_numbers)

[[[0.91679328 0.71382841 0.88348355 0.07670701 0.68204596]
  [0.49272079 0.80471348 0.67912921 0.11977653 0.45329599]
  [0.76781506 0.42089336 0.81615995 0.32910856 0.61459305]
  [0.25034363 0.94273186 0.57072506 0.14189719 0.57677628]
  [0.22720651 0.56507235 0.77526876 0.92580374 0.4959362 ]
  [0.48461594 0.35726314 0.8382965  0.18374776 0.05570593]
  [0.76981706 0.74853383 0.61892622 0.81315412 0.74740363]
  [0.53958235 0.01074977 0.51493911 0.79973651 0.45419456]
  [0.97428608 0.32326245 0.21943799 0.98398075 0.14814902]
  [0.30245311 0.85919913 0.31066239 0.432165   0.19098212]
  [0.92162435 0.50519166 0.48965047 0.58042785 0.15848337]]]


In [ ]:
lista = []
for i in range(5):
  lista.append(int(input("Digite um número: ")))

arr = np.array(lista)


In [99]:
arr = np.array([int(input("Digite um número: ")) for i in range(5)])
print(arr)

Digite um número: 5
Digite um número: 6
Digite um número: 7
Digite um número: 8
Digite um número: 10
[ 5  6  7  8 10]
