<a href="https://colab.research.google.com/github/RogerioTiuma/EspecializacaoCesar/blob/main/Exerc%C3%ADcio_01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercício 01 - Numpy

Nome dos integrantes do grupo: (Grupo:
Allan /
Fábio /
Rogério /
Ruy)

Questão 01. Você é um pesquisador de clima e deseja registrar as temperaturas diárias de uma cidade. Peça ao usuário para inserir as temperaturas de 7 dias consecutivos e, em seguida, exiba a temperatura média, a temperatura máxima, mínima, o dia em que a temperatura foi mais baixa e o dia que a temperatura foi mais alta.

In [ ]:
arr = np.array([float(input("Insira a temperatura do dia: ")) for i in range(7)])
menor_valor = np.min(arr)
index_menor = np.argmin(arr)
maior_valor = np.max(arr)
index_maior = np.argmax(arr)
media = np.mean(arr)
print(f"A temperatura média é: {media}")
print(f"Temperatura máxima:: {maior_valor}")
print(f"Temperatura mínima: {menor_valor}")
print(f"Temperatura máxima:: {maior_valor}")
print(f"Temperatura mínima: {menor_valor}")
print(f"Dia Temperatura máxima: {index_maior + 1}")
print(f"Dia Temperatura mínima: {index_menor + 1}")

Questão 02. Você está trabalhando em um projeto de engenharia e deseja calcular a força resultante de várias forças. Solicite ao usuário para inserir os valores de 5 forças e, em seguida, calcule e exiba a força resultante (soma das forças).

In [ ]:
forcas = []

for i in range(5):
    forca = float(input("Insira o valor da força: "))
    forcas.append(forca)

forcas_array = np.array(forcas)

forca_resultante = np.sum(forcas_array)

print(f"Força resultante: {forca_resultante}")

Questão 03. Você está trabalhando com um sistema de mapeamento e precisa realizar operações de indexação e fatiamento em um mapa representado por uma matriz. O mapa possui números inteiros aleatórios, e você precisa acessar os valores em posições específicas.

1.   Crie uma matriz bidimensional (um mapa) com números inteiros aleatórios entre 1 e 100. Peça ao usuário para inserir o número de linhas e colunas para o mapa.
2.   Solicite ao usuário que escolha uma linha e uma coluna no mapa.
3.   Exiba o valor encontrado na posição escolhida.

In [12]:
import numpy as np

colunas = int(input("Insira o número de linhas: "))
linhas = int(input("Insira o número de colunas:"))

random_numbers = np.random.randint(1,100,(linhas,colunas))
print("Mapa: ")
print(random_numbers)

dig_linhas = int(input("Insira a linha desejada: "))
dig_colunas = int(input("Insira a coluna desejada: "))

print(f"Valor na posição ({dig_linhas}, {dig_colunas}): {random_numbers[dig_linhas, dig_colunas]}")

Insira o número de linhas: 10
Insira o número de colunas:10
Mapa: 
[[36 97  4  5 85 56 49 28 89 41]
 [87 94 24 22 45 77 15 75 65 23]
 [90  5 41 88 24 12 81 16 53 13]
 [40 63 51 77 89 19  1 49 75 85]
 [28 87 92  2 62 80 54 33 65 28]
 [60 85 49 65  9 50 57 46 49 48]
 [41 80 88 74 41 80 52 78 10 22]
 [27 99 99 64 62 73  4 34 91 83]
 [76 84 80 48 19 93 91 23 95 40]
 [21 51 82 60 71 53 45 80 40 76]]
Insira a linha desejada: 5
Insira a coluna desejada: 2
Valor na posição (5, 2): 49


Questão 04. Você está trabalhando em um projeto de pesquisa de mercado e deseja calcular as estatísticas de idade de um grupo de pessoas. Peça ao usuário para inserir as idades de 10 pessoas e, em seguida, calcule e exiba a média, a mediana e o desvio padrão das idades.

In [ ]:
idades = np.array([int(input("Insira a idade: ")) for i in range(10)])
media = np.mean(idades)
mediana = np.median(idades)
desv_pad = np.std(idades)
print(f"Média das idades: {media}")
print(f"Mediana das idades: {mediana}")
print(f"Desvio padrão das idades: {desv_pad}")

Questão 05. Você está construindo um simulador de lançamento de dados e deseja gerar números aleatórios. Peça ao usuário para inserir o número de vezes que deseja lançar um dado de 6 faces. Em seguida, gere e exiba um vetor NumPy com os resultados desses lançamentos.

In [13]:
num_lancamentos = int(input("Insira o número de lançamentos: "))

resultado = np.random.randint(1, 7, num_lancamentos)

print(f"Resultados dos lançamentos:{resultado}")

Insira o número de lançamentos: 10
Resultados dos lançamentos:[3 3 3 2 2 3 6 5 2 6]


Questão 06. Você é um fotógrafo digital e está trabalhando em um projeto de processamento de imagens. Crie um array NumPy que represente uma imagem em escala de cinza com valores aleatórios. Normalize a imagem dividindo todos os valores pelo valor máximo possível (255). Exiba a imagem original e a imagem normalizada.

Questão 07. Neste exercício, você atua como um analista financeiro que lida com dados de investimentos. Considere o preço de fechamento diário de ações de uma empresa ao longo de uma semana. Crie um programa que execute as seguintes operações:

Solicite ao usuário que insira os preços de fechamento diários da ação da empresa durante uma semana (7 dias). Armazene esses preços em um array NumPy.

1. Calcule o retorno diário da ação, que é a diferença entre o preço de fechamento atual e o preço de fechamento do dia anterior.
2. Calcule o retorno médio diário da ação.
3. Calcule o desvio padrão dos retornos diários, que é uma medida de volatilidade.

Questão 08. Você é responsável pelo controle de estoque de uma loja e deseja identificar quais produtos estão em baixo estoque. Crie um programa que permita ao usuário inserir o nome e a quantidade em estoque de vários produtos. Após inserir os dados de todos os produtos, o programa deverá usar o NumPy para identificar e exibir uma lista dos produtos que têm menos de uma quantidade específica em estoque.

Instruções:

1. Solicite ao usuário quantos produtos deseja inserir.
2. Solicite a quantidade mínima em estoque que define o limite de "baixo estoque".
3. Para cada produto, solicite o nome e a quantidade em estoque.
4. Após inserir todos os produtos, use o NumPy para identificar os produtos que têm uma quantidade em estoque inferior à quantidade mínima especificada.