# Lista de Exercício 01 - Numpy

Nome dos integrantes do grupo: (Grupo:
Allan /
Fábio Cardoso /
Rogério Fernandes /
Ruy)

Primeiro vamos importar o numpy, que será utilizado em todas as questões

In [ ]:
import numpy as np

Questão 01. Você é um pesquisador de clima e deseja registrar as temperaturas diárias de uma cidade. Peça ao usuário para inserir as temperaturas de 7 dias consecutivos e, em seguida, exiba a temperatura média, a temperatura máxima, mínima, o dia em que a temperatura foi mais baixa e o dia que a temperatura foi mais alta.

In [ ]:
arr = np.array([float(input("Insira a temperatura do dia: ")) for i in range(7)])
menor_valor = np.min(arr)
index_menor = np.argmin(arr)
maior_valor = np.max(arr)
index_maior = np.argmax(arr)
media = np.mean(arr)
print(f"A temperatura média é: {media}")
print(f"Temperatura máxima: {maior_valor}")
print(f"Temperatura mínima: {menor_valor}")
print(f"Temperatura máxima: {maior_valor}")
print(f"Temperatura mínima: {menor_valor}")
print(f"Dia Temperatura máxima: {index_maior + 1}")
print(f"Dia Temperatura mínima: {index_menor + 1}")

Insira a temperatura do dia: 20
Insira a temperatura do dia: 14
Insira a temperatura do dia: 33
Insira a temperatura do dia: 21
Insira a temperatura do dia: 45
Insira a temperatura do dia: 22
Insira a temperatura do dia: 16
A temperatura média é: 24.428571428571427
Temperatura máxima: 45.0
Temperatura mínima: 14.0
Temperatura máxima: 45.0
Temperatura mínima: 14.0
Dia Temperatura máxima: 5
Dia Temperatura mínima: 2


Questão 02. Você está trabalhando em um projeto de engenharia e deseja calcular a força resultante de várias forças. Solicite ao usuário para inserir os valores de 5 forças e, em seguida, calcule e exiba a força resultante (soma das forças).

In [ ]:
forcas = []

for i in range(5):
    forca = float(input("Insira o valor da força: "))
    forcas.append(forca)

forcas_array = np.array(forcas)

forca_resultante = np.sum(forcas_array)

print(f"Força resultante: {forca_resultante}")

Questão 03. Você está trabalhando com um sistema de mapeamento e precisa realizar operações de indexação e fatiamento em um mapa representado por uma matriz. O mapa possui números inteiros aleatórios, e você precisa acessar os valores em posições específicas.

1.   Crie uma matriz bidimensional (um mapa) com números inteiros aleatórios entre 1 e 100. Peça ao usuário para inserir o número de linhas e colunas para o mapa.
2.   Solicite ao usuário que escolha uma linha e uma coluna no mapa.
3.   Exiba o valor encontrado na posição escolhida.

In [ ]:
colunas = int(input("Insira o número de linhas: "))
linhas = int(input("Insira o número de colunas:"))

random_numbers = np.random.randint(1,100,(linhas,colunas))
print("Mapa: ")
print(random_numbers)

dig_linhas = int(input("Insira a linha desejada: "))
dig_colunas = int(input("Insira a coluna desejada: "))

print(f"Valor na posição ({dig_linhas}, {dig_colunas}): {random_numbers[dig_linhas-1, dig_colunas-1]}")

Questão 04. Você está trabalhando em um projeto de pesquisa de mercado e deseja calcular as estatísticas de idade de um grupo de pessoas. Peça ao usuário para inserir as idades de 10 pessoas e, em seguida, calcule e exiba a média, a mediana e o desvio padrão das idades.

In [ ]:
idades = np.array([int(input("Insira a idade: ")) for i in range(10)])
media = np.mean(idades)
mediana = np.median(idades)
desv_pad = np.std(idades)
print(f"Média das idades: {media}")
print(f"Mediana das idades: {mediana}")
print(f"Desvio padrão das idades: {desv_pad}")

Questão 05. Você está construindo um simulador de lançamento de dados e deseja gerar números aleatórios. Peça ao usuário para inserir o número de vezes que deseja lançar um dado de 6 faces. Em seguida, gere e exiba um vetor NumPy com os resultados desses lançamentos.

In [ ]:
num_lancamentos = int(input("Insira o número de lançamentos: "))

resultado = np.random.randint(1, 7, num_lancamentos)

print(f"Resultados dos lançamentos:{resultado}")

Questão 06. Você é um fotógrafo digital e está trabalhando em um projeto de processamento de imagens. Crie um array NumPy que represente uma imagem em escala de cinza com valores aleatórios. Normalize a imagem dividindo todos os valores pelo valor máximo possível (255). Exiba a imagem original e a imagem normalizada.

In [ ]:
linhas = int(input("Digite o número de linhas da imagem: "))
colunas = int(input("Digite o número de colunas da imagem: "))

matriz = np.random.randint(0, 256, (linhas, colunas))
print("Imagem original:")
print(matriz)

mat_norm = matriz / 255
print("")
print("Imagem normalizada:")
print(mat_norm)

Digite o número de linhas da imagem: 10
Digite o número de colunas da imagem: 10
Imagem original:
[[ 80 246  91 221 113   3 201  40 137 167]
 [113 197 114 251  85 215  90  32 209   3]
 [237  32 125  16 200  52  62  24  67  56]
 [130 229 224 139 109  94 249 166  36 254]
 [173  38 190 241 170  38 172 212 225 165]
 [238 221 224 196  89 215 132 136 139  33]
 [112  19  11 164 231 239 228 231 148 155]
 [158  12  86  74  49 126  22 120 112 159]
 [ 30  67 203 119 129 141 126 120 106   6]
 [ 87 157 226 247 155 223  57 104  48  75]]

Imagem normalizada:
[[0.31372549 0.96470588 0.35686275 0.86666667 0.44313725 0.01176471
  0.78823529 0.15686275 0.5372549  0.65490196]
 [0.44313725 0.77254902 0.44705882 0.98431373 0.33333333 0.84313725
  0.35294118 0.1254902  0.81960784 0.01176471]
 [0.92941176 0.1254902  0.49019608 0.0627451  0.78431373 0.20392157
  0.24313725 0.09411765 0.2627451  0.21960784]
 [0.50980392 0.89803922 0.87843137 0.54509804 0.42745098 0.36862745
  0.97647059 0.65098039 0.14117647 0.

Questão 07. Neste exercício, você atua como um analista financeiro que lida com dados de investimentos. Considere o preço de fechamento diário de ações de uma empresa ao longo de uma semana. Crie um programa que execute as seguintes operações:

Solicite ao usuário que insira os preços de fechamento diários da ação da empresa durante uma semana (7 dias). Armazene esses preços em um array NumPy.

1. Calcule o retorno diário da ação, que é a diferença entre o preço de fechamento atual e o preço de fechamento do dia anterior.
2. Calcule o retorno médio diário da ação.
3. Calcule o desvio padrão dos retornos diários, que é uma medida de volatilidade.

In [ ]:
precos = np.array([float(input(f"Digite o preço de fechamento do dia {i + 1}: ")) for i in range(7)])

retorno_diario = np.diff(precos)
retorno_medio = np.mean(retorno_diario)
desv_pad_rd = np.std(retorno_diario)

print(f"Retorno médio diário: {retorno_medio:.2f}")
print(f"Desvio padrão dos retornos diários: {desv_pad_rd:.2f}")

Questão 08. Você é responsável pelo controle de estoque de uma loja e deseja identificar quais produtos estão em baixo estoque. Crie um programa que permita ao usuário inserir o nome e a quantidade em estoque de vários produtos. Após inserir os dados de todos os produtos, o programa deverá usar o NumPy para identificar e exibir uma lista dos produtos que têm menos de uma quantidade específica em estoque.

Instruções:

1. Solicite ao usuário quantos produtos deseja inserir.
2. Solicite a quantidade mínima em estoque que define o limite de "baixo estoque".
3. Para cada produto, solicite o nome e a quantidade em estoque.
4. Após inserir todos os produtos, use o NumPy para identificar os produtos que têm uma quantidade em estoque inferior à quantidade mínima especificada.

In [ ]:
quant_prod = int(input("Quantos produtos deseja inserir? "))
baixo_estoque = int(input("Qual é a quantidade mínima para considerar baixo estoque? "))

lista_prod = []
lista_estoque = []

for i in range(quant_prod):
  produto = input(f"Digite o nome do produto {i + 1}: ")
  lista_prod.append(produto)
  em_estoque = int(input(f"Digite a quantidade em estoque para {produto}: "))
  lista_estoque.append(em_estoque)

arr_produtos = np.array(lista_prod)
arr_estoque = np.array(lista_estoque)

arr_abaixo = np.where(arr_estoque < baixo_estoque)
prod_abaixo = arr_produtos[arr_abaixo]

print(f"Produtos em baixo estoque (menos de {baixo_estoque} unidades):")
for i in range(len(prod_abaixo)):
  print(prod_abaixo[i - 1])

Quantos produtos deseja inserir? 3
Qual é a quantidade mínima para considerar baixo estoque? 5
Digite o nome do produto 1: armário
Digite a quantidade em estoque para armário: 2
Digite o nome do produto 2: cadeira
Digite a quantidade em estoque para cadeira: 10
Digite o nome do produto 3: mesa
Digite a quantidade em estoque para mesa: 5
Produtos em baixo estoque (menos de 5 unidades):
armário
